config/routes.rb
require 'omniauth'
require 'omniauth-google-oauth2'
Rails.application.routes.draw do
  

  root :to  => 'users#welcome'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :events
    resources :users do
      get '/mygmails/sort' => 'mygmails#sort'
      get 'calendar' => 'users#calendar'
      get 'welcome' => 'users#welcome'
     
      resources :mygmails
        get 'getgmails' => 'mygmails#getGmails'
      
      end
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string
#  psw                    :string
#  account                :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  provider               :string
#  uid                    :string
#  token                  :string
#

require 'omniauth'
class User < ActiveRecord::Base
  #attr_accessible :name, :account, :psw  
  #attr_accessible :email, :password, :password_confirmation
  has_many :mygmails
  has_many :events , :through => :mygmails

  
  
  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
      data = access_token.info
      user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    
      if user
        user.token = access_token["credentials"]["token"]
        return user
      else
        registered_user = User.where(:email => access_token.info.email).first
        if registered_user
          registered_user.token = access_token["credentials"]["token"]
          return registered_user
        else
          user = User.create(
            name: data["name"],
            provider:access_token.provider, 
            email: data["email"],
            uid: access_token.uid,
            token: access_token["credentials"]["token"],
            password: Devise.friendly_token[0,20],
          )
        end
     end
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

     
         
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  respond_to :html
  
  def index
    @users = User.all
    respond_with(@users)
  end

  def show
    respond_with(@user)
  end

  def new
    @user = User.new
    respond_with(@user)
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_with(@user)
  end

  def update
    @user.update(user_params)
    respond_with(@user)
  end

  def destroy
    @user.destroy
    respond_with(@user)
  end
  
  def calendar
    render 'calendar'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :psw, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label 'Please type in your Gmail password', :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :psw, :class => 'text_field' %>
    </div>
	
  </div>
  <!--div class="control-group">
    <%= f.label :account, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :account, :class => 'text_field' %>
    </div>
  </div-->
  <!--div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :encrypted_password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :encrypted_password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_token, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reset_password_token, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_sent_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reset_password_sent_at, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :remember_created_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :remember_created_at, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_sign_in_at, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_sign_in_at, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_sign_in_ip, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_sign_in_ip, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :provider, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :provider, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :uid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :uid, :class => 'text_field' %>
    </div>
  </div-->

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/calendar.html.erb
<%- model_class = User -%>
<div class="actions">
<%= link_to 'Back', users_path, :class => 'btn btn-primary' %>
</div>

<!-- <% id = user_calendar_path.match(/\d/)[0].to_i%> -->
<% id = params[:user_id]%>
<% current_email = User.find(id).email%>
<% current_name = current_email.match(/(\w+.?\w+)@(\w+\.\w+)/)[1]%>
<% current_com = current_email.match(/(\w+)@(\w+\.\w+)/)[2]%>
<% url = "https://www.google.com/calendar/embed?src="+ current_name+"%40" + current_com +"&ctz=America/New_York"%>

<iframe src= "<%= url%>" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <!-- <th><%= model_class.human_attribute_name(:psw) %></th> -->
      <!-- <th><%= model_class.human_attribute_name(:account) %></th> -->
      <th><%= model_class.human_attribute_name(:email) %></th>
      <!-- <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th> -->
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_ip) %></th>
      <!-- <th><%= model_class.human_attribute_name(:last_sign_in_ip) %></th> -->
      <!-- <th><%= model_class.human_attribute_name(:provider) %></th> -->
      <th><%= model_class.human_attribute_name(:uid) %></th>
      <!-- <th><%= model_class.human_attribute_name(:created_at) %></th> -->
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <!-- <td><%= user.psw %></td>
        <td><%= user.account %></td> -->
        <td><%= user.email %></td>
        <!-- <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td> -->
        <!-- <td><%= user.remember_created_at %></td> -->
        <!-- <td><%= user.current_sign_in_at %></td> -->
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        <!-- <td><%= user.last_sign_in_ip %></td>
        <td><%= user.provider %></td> -->
        <td><%= user.uid %></td>
        <!-- <td><%=l user.created_at %></td> -->
        <td>
			<%if user.id == current_user.id%>
				<%= link_to 'Show', user,:class => 'btn btn-mini' %>
          	  	<%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <!-- <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %> -->
			  <% end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% url = current_user.psw.nil? || current_user.psw.empty? ? edit_user_path(current_user) : user_getgmails_path(current_user.id)%>

	<%= form_tag(url, :method => "get") do %>
	    <%= label_tag(:q, "Please choose date:") %>
	    <%= text_field_tag(:q) %>
	    <%= submit_tag "Get my Gmails" %>
	<% end %>
	
<script>
    $(function() {
       $( "#q" ).datepicker({
            appendText:"(yy-mm-dd)",
            dateFormat:"yy-mm-dd",
         });
    });
</script>
	
	<!-- <%= link_to t('.new', :default => t("helpers.links.new")),
	            new_user_path,
	            :class => 'btn btn-primary' %> -->

	
		
		<!-- The following code is to realize the jQuery UI datepicker feature -->
		
	<!-- <%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %> -->

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:psw) %>:</strong></dt>
  <dd><%= @user.psw %></dd>
  <!--<dt><strong><%= model_class.human_attribute_name(:account) %>:</strong></dt>
  <dd><%= @user.account %></dd> -->
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <!-- <dt><strong><%= model_class.human_attribute_name(:encrypted_password) %>:</strong></dt>
  <dd><%= @user.encrypted_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_token) %>:</strong></dt>
  <dd><%= @user.reset_password_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_sent_at) %>:</strong></dt>
  <dd><%= @user.reset_password_sent_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_created_at) %>:</strong></dt>
  <dd><%= @user.remember_created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_at) %>:</strong></dt>
  <dd><%= @user.current_sign_in_at %></dd> -->
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_at) %>:</strong></dt>
  <dd><%= @user.last_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.current_sign_in_ip %></dd>
	<% @user.password = @user.psw%>
	<% @user.save%>
  <!-- <dt><strong><%= model_class.human_attribute_name(:last_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.last_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:provider) %>:</strong></dt>
  <dd><%= @user.provider %></dd> -->
  <!--<dt><strong><%= model_class.human_attribute_name(:uid) %>:</strong></dt>
  <dd><%= @user.uid %></dd>-->
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn'  %>
  <!-- <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %> -->
  <!-- <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %> -->
</div>

app/views/users/welcome.html.erb
<%- model_class = User -%>



<% id = current_user.id %>

<div><h2>Hi, <%= User.find(id).name%> </h2></div>
<div> Current time: <%= Time.now %> </div>
<% if User.find(id).events.count == 0%>

<h3>Let's start adding events :)<h3>
<%= link_to 'Start', users_path, :class => 'btn btn-primary' %>

<% else%>
<div>Number of emails parsed: <%= User.find(id).mygmails.count %></div>
<div>Number of events added: <%= User.find(id).events.count%></div>

<% max_id =  User.find(id).events.maximum("id")%>
<% event = User.find(id).events.find(max_id)%>
<div>Latest event added: <%= event.name %></div>
<div>Scheduled time: <%= event.schedule%></div>
<div>We've saved you <%= User.find(id).events.count * 2 %> seconds.</div>
<div>Press Calendar to preview Calendar :)</div>

<%= link_to 'Calendar', "/users/#{current_user.id}/calendar", :class => 'btn btn-danger' %>
<%= link_to 'User', users_path, :class => 'btn btn-primary' %>


<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<div>
	<%= bar_chart [["Emails parsed", User.find(id).mygmails.count], ["Events added", User.find(id).events.count]] %>
</div>
<div>
	<%= pie_chart User.find(id).events.group(:name).count %>
</div>

<%end%>