config/routes.rb
require 'omniauth'
require 'omniauth-google-oauth2'
Rails.application.routes.draw do
  

  root :to  => 'users#welcome'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :events
    resources :users do
      get '/mygmails/sort' => 'mygmails#sort'
      get 'calendar' => 'users#calendar'
      get 'welcome' => 'users#welcome'
     
      resources :mygmails
        get 'getgmails' => 'mygmails#getGmails'
      
      end
  

end

app/models/mygmail.rb
# == Schema Information
#
# Table name: mygmails
#
#  id         :integer          not null, primary key
#  eid        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  content    :text
#

class Mygmail < ActiveRecord::Base
  has_many :events
  belongs_to :users
  validates :user_id, presence: true
end

app/controllers/mygmails_controller.rb
require 'gmail'
require 'date'
require 'google/api_client'
require_relative 'events_controller'
require 'active_support/time'
class MygmailsController < ApplicationController

  before_action :set_user , except: [:addevent ]

  respond_to :html
  def getGmails 
    
    start = DateTime.parse(params[:q])
    Gmail.connect(@user.email, @user.psw) do |gmail|
      break unless gmail.logged_in?
      gmail.inbox.emails(:after => start ).each do |email|
        flag = false
        if Mygmail.where(:eid => email.uid, :user_id =>@user.id).empty?
          flag = true
          event_name = email.subject
          if email.text_part.nil?
            text = email.body.to_s
          else
            text = email.text_part.body.to_s 
          end
          # parser method needed here
          event_schedule = parsetime text
          @mygmail =  @user.mygmails.create(:eid => email.uid, :user_id => @user.id, :content =>text)
          @mygmail.save
          # if no event_schedule then event is not added
          @event = @mygmail.events.create(:mygmail_id => @mygmail.id, :schedule => event_schedule, :name=> event_name) unless event_schedule.nil? 
          @event.save
        end
        # addevent if flag
        addevent @user if flag
      end
    end
    
    @mygmail = @user.mygmails.all
    render :template => "mygmails/index"
  end
  
  # add event to google calendar
  def addevent user
    @mygmail = user.mygmails.all

    client = Google::APIClient.new
    client.authorization.access_token = user.token
    service = client.discovered_api('calendar', 'v3')
    @mygmail.each do |g|
      g.events.all.each do |e|
        unless e.schedule.nil?
          _tocal = {
            'summary' => e.name,
              'description' => e.name,
              'location' => e.location,
              'start' => {
                  'dateTime' => e.schedule.to_datetime.rfc3339},
              'end' => {
                  'dateTime' => ((e.schedule.to_datetime + 2.0/24).rfc3339)},
              'attendees' => { "email" => user.email }
        }
        
          @set_event = client.execute(
                                  :api_method => service.events.insert,
                                  :parameters => {'calendarId' => user.email, 'sendNotifications' => true},
                                  :body => JSON.dump(_tocal),
                                  :headers => {'Content-Type' => 'application/json'})
                                

        end                
      end
    end
  end
  
  def parsetime text
    zone = "Eastern Time (US & Canada)"
      text.lines.each do |l| 
        # 2014-11-20
        if m = /\d{2,4}-\d{1,2}-\d{1,2}/.match(l)
          date = ActiveSupport::TimeZone[zone].parse(m[0])
          return date
        end
        #2014/11/20
        if m = /\d{4}\/\d{1,2}\/\d{1,2}/.match(l)
          date = ActiveSupport::TimeZone[zone].parse(m[0])
          return date
        end
        
        #/11/20/2014
        if m = /(\d{1,2}\/\d{1,2})\/(\d{4})/.match(l)
          temp = m[2]+'/'+m[1]
          # date = DateTime.strptime(m[0],'%m/%d/%Y').in_time_zone("EST")
          date = ActiveSupport::TimeZone[zone].parse(temp)
          return date
        end
        
        # #11/20
        # if m = /\d{2,4}\/\d{1,2}\/\d{1,2}/.match(l)
        #   date = ActiveSupport::TimeZone[zone].parse(m[0])
        #   return date
        # end
        
    end
  end
  
  def index
    @mygmail = @user.mygmails.all
    respond_with(@user, @mygmail)
  end

  def show
    @mygmail = @user.mygmails.find(params[:id])
    respond_with(@user, @mygmail)
  end

  def new
    @mygmail = @user.mygmails.build
    
    respond_with(@user, @mygmail)
  end

  def edit
    @mygmail = @user.mygmails.find(params[:id])
    respond_with(@user, @mygmail)
  end

  def create
   
    @mygmail = @user.mygmails.create(mygmail_params)
    
    if @mygmail.save
      respond_with(@user,@mygmail)
    else
      
    end
  end

  def update
    
    @mygmail = @user.mygmails.find(params[:id])
    @mygmail.update(mygmail_params)
    respond_with(@user, @mygmail)
  end

  def destroy
    
    @mygmail = @user.mygmails.find(params[:id])
    @mygmail.destroy
    respond_with(@user, @mygmail)
  end
  
  def sort
    # @mygmails = []
    # if (Mygmail.attribute_names.include? (params[:field])) then
    @mygmail = Mygmail.order(:eid)
    # end
    render :index
  end

  private
    def set_user
      @user = User.find(params[:user_id])
     
    end

    def mygmail_params
      params.require(:mygmail).permit(:eid)
    end
end

app/helpers/mygmails_helper.rb
module MygmailsHelper
end

app/views/mygmails/_form.html.erb
<%= form_for [@user, @mygmail], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :eid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :eid, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_mygmails_path(@user), :class => 'btn' %>
  </div>
<% end %>

app/views/mygmails/edit.html.erb
<%- model_class = Mygmail -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mygmails/index.html.erb
<%- model_class = Mygmail -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="actions">
<%= link_to 'Sort by eid', user_mygmails_sort_path, :class => 'btn btn-primary' %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:eid) %></th>
	  <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
	<%unless @mygmail.nil?%>
	    <% @mygmail.each do |mygmail| %>
		<%next if mygmail.id.nil?%>
	      <tr>
	        <td><%= link_to mygmail.id, user_mygmail_path(@user,mygmail) %></td>
	        <td><%= mygmail.eid %></td>
			<td><%= mygmail.content %></td>
	        <td><%=l mygmail.created_at %></td>
	        <td>
	          <%= link_to t('.edit', :default => t("helpers.links.edit")),
	                      edit_user_mygmail_path(@user, mygmail), :class => 'btn btn-mini' %>
	          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
	                      user_mygmail_path(@user, mygmail),
	                      :method => :delete,
	                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
	                      :class => 'btn btn-mini btn-danger' %>
	        </td>
	      </tr>
	    <% end %>
	<% end %>
  </tbody>
</table>


	  <!--%= datetime_local_field :getGmails%-->
    <!--%= text_field_tag :search, params[:search] %-->
	<!--%= select_date Date.today, prefix: :start_date %-->
	<!--%= link_to 'Click me', :url => {:controller => 'mygmails', :action => 'action', :submit => 'field_to_submit', :method => :post, :remote => true} %-->

	



<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_mygmail_path(@user),
            :class => 'btn btn-primary' %>

app/views/mygmails/new.html.erb
<%- model_class = Mygmail -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mygmails/show.html.erb
<%- model_class = Mygmail -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:eid) %>:</strong></dt>
  <dd><%= @mygmail.eid %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              user_mygmails_path(@user), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_mygmail_path(@user,@mygmail), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_mygmail_path(@user,@mygmail),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>